import re
from typing import Dict, Any, Optional

def clean_text(text: str) -> str:
    """Cleans up leading/trailing whitespaces and newlines from extracted text."""
    if not text:
        return ""
    return text.strip()

def parse_question_xml(xml_content: str) -> Optional[Dict[str, Any]]:
    """
    Parses XML content generated by the AI.
    Handles both standard and group questions.
    Returns a dictionary representing the structured data, or None if parsing fails.
    """
    # 1. Try to find a group question first
    group_match = re.search(r"<group_question\s*>(.*?)</group_question\s*>", xml_content, re.DOTALL | re.IGNORECASE)
    if group_match:
        group_content = group_match.group(1)
        
        # Extract context
        context_match = re.search(r"<context\s*>(.*?)</context\s*>", group_content, re.DOTALL | re.IGNORECASE)
        context = clean_text(context_match.group(1)) if context_match else ""
        
        # Extract all sub-questions
        question_matches = re.findall(r"<question\s*>(.*?)</question\s*>", group_content, re.DOTALL | re.IGNORECASE)
        questions = []
        for q_content in question_matches:
            stem_match = re.search(r"<stem\s*>(.*?)</stem\s*>", q_content, re.DOTALL | re.IGNORECASE)
            stem = clean_text(stem_match.group(1)) if stem_match else ""
            
            option_matches = re.findall(r"<option\s*>(.*?)</option\s*>", q_content, re.DOTALL | re.IGNORECASE)
            options = [clean_text(opt) for opt in option_matches]
            
            questions.append({
                "stem": stem,
                "options": options
            })
            
        if not questions:
            return None
            
        return {
            "is_group": True,
            "context": context,
            "questions": questions
        }

    # 2. Otherwise, look for a single question
    question_match = re.search(r"<question\s*>(.*?)</question\s*>", xml_content, re.DOTALL | re.IGNORECASE)
    if question_match:
        q_content = question_match.group(1)
        
        stem_match = re.search(r"<stem\s*>(.*?)</stem\s*>", q_content, re.DOTALL | re.IGNORECASE)
        stem = clean_text(stem_match.group(1)) if stem_match else ""
        
        option_matches = re.findall(r"<option\s*>(.*?)</option\s*>", q_content, re.DOTALL | re.IGNORECASE)
        options = [clean_text(opt) for opt in option_matches]
        
        return {
            "is_group": False,
            "stem": stem,
            "options": options
        }
        
    return None
