import re
from typing import Dict, Any, List, Optional

def clean_text(text: str) -> str:
    """Cleans up leading/trailing whitespaces and newlines from extracted text."""
    if not text:
        return ""
    return text.strip()

def check_and_clean_options(options: List[str]) -> List[str]:
    """
    Checks if all elements in the options list are prefixed with matching alphabetical labels (e.g. A., B., C., D.),
    and if so, strips the prefix and returns the cleaned options.
    """
    if not isinstance(options, list) or len(options) < 2:
        return options
        
    cleaned = []
    matches_all = True
    
    for i, opt in enumerate(options):
        if not isinstance(opt, str):
            matches_all = False
            break
        # Expected letters for index i: 'A'/'a' for 0, 'B'/'b' for 1, etc.
        upper_char = chr(65 + i)
        lower_char = chr(97 + i)
        
        # Regex to match prefix: letter, followed by divider (. or ) or : or - or space), followed by optional space
        pattern = rf"^\s*([{upper_char}{lower_char}])\s*([\.\)\:\-\s])\s*(.*)"
        match = re.match(pattern, opt, re.DOTALL)
        
        if match:
            cleaned.append(match.group(3))
        else:
            matches_all = False
            break
            
    if matches_all:
        return cleaned
    return options

def parse_question_xml(xml_content: str) -> Optional[Dict[str, Any]]:
    """
    Parses XML content generated by the AI.
    Handles both standard and group questions.
    Returns a dictionary representing the structured data, or None if parsing fails.
    """
    # 1. Try to find a group question first
    group_match = re.search(r"<group_question\s*>(.*?)</group_question\s*>", xml_content, re.DOTALL | re.IGNORECASE)
    if group_match:
        group_content = group_match.group(1)
        
        # Extract context
        context_match = re.search(r"<context\s*>(.*?)</context\s*>", group_content, re.DOTALL | re.IGNORECASE)
        context = clean_text(context_match.group(1)) if context_match else ""
        
        # Extract all sub-questions
        question_matches = re.findall(r"<question\s*>(.*?)</question\s*>", group_content, re.DOTALL | re.IGNORECASE)
        questions = []
        for q_content in question_matches:
            stem_match = re.search(r"<stem\s*>(.*?)</stem\s*>", q_content, re.DOTALL | re.IGNORECASE)
            stem = clean_text(stem_match.group(1)) if stem_match else ""
            
            option_matches = re.findall(r"<option\s*>(.*?)</option\s*>", q_content, re.DOTALL | re.IGNORECASE)
            options = [clean_text(opt) for opt in option_matches]
            options = check_and_clean_options(options)
            
            answer_match = re.search(r"<answer\s*>(.*?)</answer\s*>", q_content, re.DOTALL | re.IGNORECASE)
            answer = clean_text(answer_match.group(1)) if answer_match else ""
            
            explanation_match = re.search(r"<explanation\s*>(.*?)</explanation\s*>", q_content, re.DOTALL | re.IGNORECASE)
            explanation = clean_text(explanation_match.group(1)) if explanation_match else ""
            
            questions.append({
                "stem": stem,
                "options": options,
                "answer": answer,
                "explanation": explanation
            })
            
        if not questions:
            return None
            
        return {
            "is_group": True,
            "context": context,
            "questions": questions
        }

    # 2. Otherwise, look for a single question
    question_match = re.search(r"<question\s*>(.*?)</question\s*>", xml_content, re.DOTALL | re.IGNORECASE)
    if question_match:
        q_content = question_match.group(1)
        
        stem_match = re.search(r"<stem\s*>(.*?)</stem\s*>", q_content, re.DOTALL | re.IGNORECASE)
        stem = clean_text(stem_match.group(1)) if stem_match else ""
        
        option_matches = re.findall(r"<option\s*>(.*?)</option\s*>", q_content, re.DOTALL | re.IGNORECASE)
        options = [clean_text(opt) for opt in option_matches]
        options = check_and_clean_options(options)
        
        answer_match = re.search(r"<answer\s*>(.*?)</answer\s*>", q_content, re.DOTALL | re.IGNORECASE)
        answer = clean_text(answer_match.group(1)) if answer_match else ""
        
        explanation_match = re.search(r"<explanation\s*>(.*?)</explanation\s*>", q_content, re.DOTALL | re.IGNORECASE)
        explanation = clean_text(explanation_match.group(1)) if explanation_match else ""
        
        return {
            "is_group": False,
            "stem": stem,
            "options": options,
            "answer": answer,
            "explanation": explanation
        }
        
    return None
