import argparse
from src.generation.reconstructor import OPTION_PREFIX_STYLES

def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Mock Exam Question Generator & Text Reconstructor")
    subparsers = parser.add_subparsers(dest="command", required=True, help="Refactored subcommands")

    # 1. curriculum
    p_curr = subparsers.add_parser("curriculum", help="Stage 1: Generate curriculum JSON files")
    p_curr.add_argument("--all", action="store_true", help="Generate curricula for all subjects & grades concurrently")
    p_curr.add_argument("--subject", type=str, help="Subject slug (e.g. 'physics')")
    p_curr.add_argument("--grade", type=int, help="Grade level (e.g. 11)")
    p_curr.add_argument("--model", type=str, default="deepseek-v4-pro", help="LLM model to use")
    p_curr.add_argument("--provider", type=str, choices=["deepseek", "nvidia", "vilao"], default=None, help="LLM provider to use")
    p_curr.add_argument("--thinking", type=str, default="high", choices=["high", "max", "low", "medium", "none"], help="Thinking effort level")
    p_curr.add_argument("-c", "--concurrency", type=int, default=4, help="Number of parallel workers for concurrent generation")

    # 3. reconstruct
    p_rec = subparsers.add_parser("reconstruct", help="Stage 3: Reconstruct raw text and track spans")
    p_rec.add_argument("-i", "--input-dir", type=str, default="output", help="Input directory containing questions")
    p_rec.add_argument("--in-place", action="store_true", help="Overwrite existing files directly")
    p_rec.add_argument("--reconstruct-dest", type=str, default="output/reconstructed", help="Destination folder if not in-place")
    p_rec.add_argument("-c", "--concurrency", type=int, default=4, help="Concurrency for reconstruction")
    p_rec.add_argument("--q-prefix", type=str, help="Override question prefix template")
    p_rec.add_argument("--opt-style", type=str, choices=list(OPTION_PREFIX_STYLES.keys()), help="Override option prefix style")
    p_rec.add_argument("--ord-item-style", type=str, choices=["char", "index"], help="Override ordering item style")
    p_rec.add_argument("--ord-item-template", type=str, help="Override ordering item template")
    
    # Reconstruct augmentations
    p_rec.add_argument("--typo-rate", type=float, default=0.0, help="Spelling mistake typo injection rate")
    p_rec.add_argument("--space-noise-rate", type=float, default=0.0, help="Spacing noise injection rate")
    p_rec.add_argument("--latex-mask-prob", type=float, default=0.0, help="LaTeX masking probability")
    p_rec.add_argument("--latex-placeholder", type=str, default="[LATEX]", help="LaTeX masking placeholder")
    p_rec.add_argument("--enable-permutations", action="store_true", help="Enable random permutations")
    p_rec.add_argument("--option-drop-prob", type=float, default=0.0, help="Option drop probability")
    p_rec.add_argument("--casing-noise-prob", type=float, default=0.0, help="Casing noise probability")
    p_rec.add_argument("--synonym-swap-prob", type=float, default=0.0, help="Synonym swap probability")
    p_rec.add_argument("--formatting-noise-prob", type=float, default=0.0, help="Formatting tag noise probability")
    p_rec.add_argument("--inline-option-prob", type=float, default=0.0, help="Probability of formatting options inline")
    p_rec.add_argument("--min-inline-spaces", type=int, default=5, help="Minimum random spaces to inject between inline options")
    p_rec.add_argument("--max-inline-spaces", type=int, default=30, help="Maximum random spaces to inject between inline options")
    p_rec.add_argument("--min-inline-tabs", type=int, default=1, help="Minimum random tabs to inject between inline options")
    p_rec.add_argument("--max-inline-tabs", type=int, default=3, help="Maximum random tabs to inject between inline options")
    p_rec.add_argument("--answer-table-format", type=str, choices=["md", "html", "csv", "random"], default=None, help="Answer table format")
    p_rec.add_argument("--answer-table-direction", type=str, choices=["horizontal", "vertical", "random"], default=None, help="Answer table direction")
    p_rec.add_argument("--answer-table-chunk-size", type=int, default=None, help="Answer table chunk size")
    p_rec.add_argument("--paraphrase-section-titles", action="store_true", help="Enable random paraphrasing of section titles")

    # 4. exam
    p_exam = subparsers.add_parser("exam", help="Stage 4: Generate mock exams as compiled JSON")
    p_exam.add_argument("-n", "--num-exams", type=int, default=300, help="Number of exams to generate")
    p_exam.add_argument("-o", "--output-dir", type=str, default="output/exams", help="Output directory path")
    p_exam.add_argument("--model", type=str, default="deepseek-v4-pro", help="LLM model to use")
    p_exam.add_argument("--provider", type=str, choices=["deepseek", "nvidia", "vilao"], default=None, help="LLM provider to use")
    p_exam.add_argument("--thinking", type=str, default="high", choices=["high", "max", "low", "medium", "none"], help="Thinking effort level")
    p_exam.add_argument("-c", "--concurrency", type=int, default=8, help="Number of concurrent threads per exam")
    p_exam.add_argument("--subject", type=str, help="Filter generation for a specific subject")
    p_exam.add_argument("--grade", type=int, help="Filter generation for a specific grade")

    # 5. prepare
    p_prep = subparsers.add_parser("prepare", help="Stage 5: Prepare tokenized datasets for training")
    p_prep.add_argument("-i", "--input-dir", type=str, default="output", help="Input folder of question files")
    p_prep.add_argument("-o", "--output-dir", type=str, default="output/dataset", help="Output folder for training dataset split")
    p_prep.add_argument("--model", type=str, default="FacebookAI/xlm-roberta-base", help="Base model/tokenizer name")
    p_prep.add_argument("--latex-placeholder", type=str, default="[LATEX]", help="Placeholder for LaTeX equations")
    p_prep.add_argument("--train-ratio", type=float, default=0.8, help="Ratio of training set")
    p_prep.add_argument("--val-ratio", type=float, default=0.1, help="Ratio of validation set")
    p_prep.add_argument("--seed", type=int, default=42, help="Seed for splitting")
    p_prep.add_argument("--exam-level", action="store_true", help="Process at exam level")
    p_prep.add_argument("--max-len", type=str, default="512,768,1024,2048", help="Sequence lengths")
    p_prep.add_argument("--stride", type=str, default="128,192,256,512", help="Strides")
    p_prep.add_argument("--typo-rate", type=float, default=0.02, help="Typo rate")
    p_prep.add_argument("--space-noise-rate", type=float, default=0.15, help="Space noise rate")
    p_prep.add_argument("--latex-mask-prob", type=float, default=0.5, help="LaTeX mask probability")
    p_prep.add_argument("--enable-permutations", action="store_true", help="Enable permutations")
    p_prep.add_argument("--option-drop-prob", type=float, default=0.05, help="Option drop probability")
    p_prep.add_argument("--casing-noise-prob", type=float, default=0.10, help="Casing noise probability")
    p_prep.add_argument("--synonym-swap-prob", type=float, default=0.10, help="Synonym swap probability")
    p_prep.add_argument("--formatting-noise-prob", type=float, default=0.10, help="Formatting tag noise probability")
    p_prep.add_argument("--inline-option-prob", type=float, default=0.0, help="Probability of formatting options inline")
    p_prep.add_argument("--min-inline-spaces", type=int, default=5, help="Minimum random spaces to inject between inline options")
    p_prep.add_argument("--max-inline-spaces", type=int, default=30, help="Maximum random spaces to inject between inline options")
    p_prep.add_argument("--min-inline-tabs", type=int, default=1, help="Minimum random tabs to inject between inline options")
    p_prep.add_argument("--max-inline-tabs", type=int, default=3, help="Maximum random tabs to inject between inline options")
    p_prep.add_argument("--answer-table-format", type=str, choices=["md", "html", "csv", "random"], default="random", help="Answer table format")
    p_prep.add_argument("--answer-table-direction", type=str, choices=["horizontal", "vertical", "random"], default="random", help="Answer table direction")
    p_prep.add_argument("--answer-table-chunk-size", type=int, default=None, help="Answer table chunk size")
    p_prep.add_argument("--no-paraphrase-section-titles", action="store_false", dest="paraphrase_section_titles", default=True, help="Disable random paraphrasing of section titles")

    # 6. train
    p_train = subparsers.add_parser("train", help="Stage 6: Train XLM-RoBERTa model with LoRA")
    p_train.add_argument("--repo_id", type=str, default="daominhwysi/synthetic-seq-labelling-vi-exam-v2", help="HF Dataset repository ID")
    p_train.add_argument("--model_name", type=str, default="FacebookAI/xlm-roberta-base", help="HF base model name")
    p_train.add_argument("--output_dir", type=str, default="./results", help="Directory to save checkpoints")
    p_train.add_argument("--epochs", type=int, default=3, help="Number of training epochs")
    p_train.add_argument("--batch_size", type=int, default=8, help="Training batch size")
    p_train.add_argument("--eval_batch_size", type=int, default=8, help="Evaluation batch size")
    p_train.add_argument("--lr", type=float, default=5e-4, help="Learning rate")
    p_train.add_argument("--lora_r", type=int, default=16, help="LoRA rank")
    p_train.add_argument("--lora_alpha", type=int, default=32, help="LoRA alpha")
    p_train.add_argument("--lora_dropout", type=float, default=0.1, help="LoRA dropout rate")
    p_train.add_argument("--use_bf16", action="store_true", help="Use bfloat16 mixed precision")
    p_train.add_argument("--no_fp16", action="store_true", help="Disable float16 mixed precision")
    p_train.add_argument("--weight_decay", type=float, default=0.01, help="Weight decay")
    p_train.add_argument("--save_total_limit", type=int, default=2, help="Max checkpoints to keep")
    p_train.add_argument("--no-lora", action="store_true", help="Disable LoRA and perform full fine-tuning")
    p_train.add_argument("--gradient-checkpointing", action="store_true", help="Enable gradient checkpointing to save memory")
    p_train.add_argument("--gradient-accumulation-steps", type=int, default=1, help="Number of update steps to accumulate before performing a backward pass")
    p_train.add_argument("--seed", type=int, default=42, help="Seed for training reproducibility")
    p_train.add_argument("--lr-scheduler-type", type=str, default="linear", help="Learning rate scheduler type")
    p_train.add_argument("--warmup-ratio", type=float, default=0.0, help="Warmup ratio for scheduler")
    p_train.add_argument("--warmup-steps", type=int, default=0, help="Warmup steps for scheduler")
    p_train.add_argument("--ema-decay", type=float, default=0.0, help="Decay rate for Exponential Moving Average (EMA)")
    p_train.add_argument("--no-class-weights", action="store_true", help="Disable class weights for cross-entropy loss penalty")
    p_train.add_argument("--real-upsample-factor", type=float, default=1.0, help="Sampling weight multiplier for real exam samples relative to synthetic ones")
    p_train.add_argument("--use-focal-loss", action="store_true", help="Enable Focal Loss to focus training gradients on hard token boundaries")
    p_train.add_argument("--focal-gamma", type=float, default=2.0, help="Focusing parameter gamma for Focal Loss")
    p_train.add_argument("--push_to_hub", action="store_true", help="Push to Hugging Face Hub")
    p_train.add_argument("--hf_token", type=str, help="Hugging Face authentication token")


    # 7. inference
    p_inf = subparsers.add_parser("inference", help="Stage 7: Run inference on sample inputs using trained model")
    p_inf.add_argument("--model_dir", type=str, default="./results", help="Model adapter directory")
    p_inf.add_argument("--base_model_name", type=str, default="FacebookAI/xlm-roberta-base", help="HF base model name")

    # 8. upload (dataset)
    p_upl = subparsers.add_parser("upload", help="Upload dataset splits to Hugging Face Hub")
    p_upl.add_argument("--token", type=str, help="HF Token")
    p_upl.add_argument("--repo-id", type=str, help="HF dataset repository target path")
    p_upl.add_argument("--dataset-dir", type=str, default="output/dataset", help="Local folder with splits")

    # 8b. upload-model
    p_upl_m = subparsers.add_parser("upload-model", help="Upload trained model/adapter checkpoint to Hugging Face Hub")
    p_upl_m.add_argument("--model-dir", type=str, default="./results", help="Path to model directory")
    p_upl_m.add_argument("--repo-id", type=str, default=None, help="HF model repository ID")
    p_upl_m.add_argument("--token", type=str, default=None, help="Hugging Face write token")
    p_upl_m.add_argument("--private", action="store_true", help="Create the repository as private")
    p_upl_m.add_argument("--commit-message", type=str, default=None, help="Custom commit message")
    p_upl_m.add_argument("--dataset-repo", type=str, default="daominhwysi/synthetic-seq-labelling-vi-exam-v2", help="HF dataset repo to reference")

    # 9. visualize
    p_vis = subparsers.add_parser("visualize", help="Generate an HTML interactive visualizer for token span labels")
    p_vis.add_argument("-i", "--input-file", type=str, default="output/dataset/train.jsonl", help="Path to jsonl file")
    p_vis.add_argument("-o", "--output-html", type=str, default="output/dataset/sample_visualization.html", help="Output path for HTML")
    p_vis.add_argument("--max-samples", type=int, default=1000, help="Maximum samples to embed")

    return parser
