import os
import sys
import json
import tempfile
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Add local path
sys.path.append(str(Path(__file__).parent.parent))

DEFAULT_DATASET_REPO = "daominhwysi/synthetic-seq-labelling-vi-exam-v2"
DEFAULT_DATASET_DIR  = "output/dataset"


# ---------------------------------------------------------------------------
# Dataset card (README.md)
# ---------------------------------------------------------------------------

def _generate_dataset_card(repo_id: str) -> str:
    return f"""\
---
language:
- vi
license: apache-2.0
task_categories:
- token-classification
task_ids:
- named-entity-recognition
tags:
- vietnamese
- exam
- sequence-labeling
- educational
- synthetic
pretty_name: Vietnamese Exam Sequence Labelling Dataset
---

# Vietnamese Exam Sequence Labelling Dataset

A synthetic + real-data dataset for **token-level sequence labelling** of Vietnamese educational exam papers.
Generated by the [sequence-labelling-data-generator](https://github.com/daominhwysi/vietnamese-exam-seq-labelling) pipeline using DeepSeek LLMs and real OCR-annotated exams.

## Task

Given raw exam text (possibly from OCR), label each token with one of the entity tags below so downstream models can automatically segment and extract structured exam components.

## Tag Set

| Tag | Description |
|---|---|
| `O` | Outside — not part of any entity |
| `B-question_label` / `I-question_label` | Question prefix indicators (`Câu 1:`, `Question 2.`) |
| `B-stem` / `I-stem` | Main question body text |
| `B-option_label` / `I-option_label` | Option letter prefixes (`A.`, `B.`, `a)`) |
| `B-option_text` / `I-option_text` | Option content text |
| `B-stimulus` / `I-stimulus` | Shared reading passage / stimulus block for group questions |
| `B-section` / `I-section` | Section headers and exam directions |

## Data Fields

Each sample in `train.jsonl`, `val.jsonl`, `test.jsonl` contains:

```json
{{
  "tokens":         ["▁Câu", "▁1", ".", "▁Cho", "..."],
  "input_ids":      [0, 12, 34, 56, ...],
  "attention_mask": [1, 1, 1, 1, ...],
  "labels":         [1, 2, 0, 3, ...],
  "tags":           ["B-question_label", "I-question_label", "O", "B-stem", ...],
  "metadata": {{
    "subject":       "physics",
    "grade":         11,
    "is_real":       false,
    "exam_id":       "exam_abc123",
    "max_len":       512,
    "stride":        128,
    "chunk_idx":     0,
    "total_chunks":  1
  }}
}}
```

Label IDs are defined in `label_mapping.json`.

## Splits

| Split | File |
|---|---|
| Train | `train.jsonl` |
| Validation | `val.jsonl` |
| Test | `test.jsonl` |

## Subjects

`economics_law`, `geography`, `history`, `math_algebra`, `math_geometry`, `physics`, `chemistry`, `english`, `literature`

## Grades

8 · 9 · 10 · 11 · 12

## XML Annotation Files

The `xml/` folder contains human-readable inline-tagged XML files reconstructed from real and synthetic exams, matching the annotation format used during data creation:

```xml
<question_label>Câu 1.</question_label> <stem>Cho phương trình $x^2 - 5x + 6 = 0$.</stem>
<option_label>A.</option_label> <option_text>x = 2 hoặc x = 3</option_text>
```

## Citation

```bibtex
@misc{{vi-exam-seq-labelling,
  title  = {{Vietnamese Exam Sequence Labelling Dataset}},
  author = {{daominhwysi}},
  year   = {{2025}},
  url    = {{https://huggingface.co/datasets/{repo_id}}}
}}
```
"""


import argparse

# ---------------------------------------------------------------------------
# Main upload function
# ---------------------------------------------------------------------------

def upload_dataset(token=None, repo_id=None, dataset_dir=None, mode="all"):
    """
    Upload dataset files to HF Hub.
    
    Modes:
      - 'all': Uploads the entire dataset folder (train/val/test splits + XMLs + label_mapping.json + raw_exams.jsonl).
      - 'online-only' (or 'raw-only'): Uploads only raw_exams.jsonl + label_mapping.json + README.md for lightweight online dynamic training.

    Args:
        token:       HF write token (falls back to HF_TOKEN env var).
        repo_id:     Target HF dataset repository ID.
        dataset_dir: Local folder containing train/val/test JSONL + label_mapping.json + xml/.
        mode:        'all' or 'online-only' / 'raw-only'.
    """
    if load_dotenv is not None:
        load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent.parent / ".env")

    if not token:
        token = os.getenv("HF_TOKEN")
    if not token:
        try:
            from huggingface_hub import get_token
            token = get_token()
        except ImportError:
            pass
    if not token:
        print("Error: HF_TOKEN not found in environment or huggingface-cli cache. Please log in with `hf auth login` or set HF_TOKEN.")
        sys.exit(1)

    if not repo_id:
        repo_id = DEFAULT_DATASET_REPO

    if not dataset_dir:
        dataset_dir = DEFAULT_DATASET_DIR

    dataset_path = Path(dataset_dir)
    if not dataset_path.exists():
        dataset_path.mkdir(parents=True, exist_ok=True)

    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        print("Error: 'huggingface_hub' is not installed.")
        sys.exit(1)

    api = HfApi(token=token)

    print(f"Ensuring repository '{repo_id}' exists on Hugging Face Hub...")
    try:
        create_repo(repo_id=repo_id, repo_type="dataset", token=token, exist_ok=True)
        print("Repository is ready.")
    except Exception as e:
        print(f"Notice during repository creation: {e}")

    # 1. Generate and upload the dataset README --------------------------------
    print("Generating dataset card (README.md)...")
    readme_content = _generate_dataset_card(repo_id)
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", encoding="utf-8", delete=False
    ) as tmp:
        tmp.write(readme_content)
        tmp_readme_path = tmp.name

    try:
        api.upload_file(
            path_or_fileobj=tmp_readme_path,
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="dataset",
            commit_message="Add dataset card (README.md)",
        )
        print("  Uploaded README.md")
    except Exception as e:
        print(f"  Warning: Could not upload README.md: {e}")
    finally:
        Path(tmp_readme_path).unlink(missing_ok=True)

    # 2. Upload according to mode --------------------------------------------
    is_online_mode = mode in ["online-only", "raw-only", "online", "raw"]
    
    if is_online_mode:
        print(f"\n[Online Mode] Uploading only raw data for online dynamic training from '{dataset_dir}' -> '{repo_id}' ...")
        raw_exams_file = dataset_path / "raw_exams.jsonl"
        label_mapping_file = dataset_path / "label_mapping.json"
        
        # Auto consolidate raw exams if not found
        if not raw_exams_file.exists():
            print("  'raw_exams.jsonl' not found. Consolidating raw exams now...")
            from src.data.prepare import consolidate_raw_exams
            consolidate_raw_exams("output", str(raw_exams_file))

        # Auto generate label mapping if not found
        if not label_mapping_file.exists():
            print("  'label_mapping.json' not found. Generating default label mapping...")
            from src.data.prepare import get_tag_mappings
            tag_to_id, id_to_tag = get_tag_mappings()
            with open(label_mapping_file, "w", encoding="utf-8") as f:
                json.dump({"tag_to_id": tag_to_id, "id_to_tag": id_to_tag}, f, indent=2, ensure_ascii=False)

        # Upload raw_exams.jsonl
        print(f"  Uploading '{raw_exams_file.name}' ({raw_exams_file.stat().st_size / (1024*1024):.2f} MB)...")
        api.upload_file(
            path_or_fileobj=str(raw_exams_file),
            path_in_repo="raw_exams.jsonl",
            repo_id=repo_id,
            repo_type="dataset",
            commit_message="Upload consolidated raw exams for online dynamic augmentation",
        )

        # Upload label_mapping.json
        print(f"  Uploading '{label_mapping_file.name}'...")
        api.upload_file(
            path_or_fileobj=str(label_mapping_file),
            path_in_repo="label_mapping.json",
            repo_id=repo_id,
            repo_type="dataset",
            commit_message="Upload label mapping for sequence labeling",
        )
        print("  Uploaded online dynamic training files successfully (raw_exams.jsonl + label_mapping.json).")

    else:
        print(f"\n[Full Offline Mode] Uploading all dataset splits + XMLs from '{dataset_dir}' -> '{repo_id}' ...")
        xml_count = len(list((dataset_path / "xml").glob("*_annotated.xml"))) if (dataset_path / "xml").exists() else 0
        if xml_count:
            print(f"  (includes {xml_count} XML annotation file(s) in xml/)")
        try:
            api.upload_folder(
                folder_path=str(dataset_path),
                repo_id=repo_id,
                repo_type="dataset",
                commit_message="Upload synthetic sequence labelling dataset for Vietnamese exams",
            )
            print(f"  Uploaded dataset splits{' + XML annotations' if xml_count else ''}.")
        except Exception as e:
            print(f"Error uploading dataset: {e}")
            sys.exit(1)

    print(f"\nSuccess! Dataset at: https://huggingface.co/datasets/{repo_id}")


def main():
    parser = argparse.ArgumentParser(description="Upload dataset splits and annotation files to Hugging Face Hub")
    parser.add_argument(
        "--dataset_repo_id",
        "--dataset-repo-id",
        "--repo-id",
        "--repo_id",
        type=str,
        default=DEFAULT_DATASET_REPO,
        dest="dataset_repo_id",
        help="Target Hugging Face Dataset repository ID (e.g. username/repo-name)"
    )
    parser.add_argument(
        "--dataset-dir",
        "--dataset_dir",
        type=str,
        default=DEFAULT_DATASET_DIR,
        help="Local dataset directory path"
    )
    parser.add_argument(
        "--mode",
        type=str,
        default="all",
        choices=["all", "online-only", "raw-only", "online", "raw"],
        help="Upload mode: 'all' (entire folder) or 'online-only' / 'raw-only' (only raw_exams.jsonl + label_mapping.json)"
    )
    parser.add_argument(
        "--token",
        type=str,
        default=None,
        help="Hugging Face authentication token (or set HF_TOKEN env var)"
    )
    args = parser.parse_args()
    upload_dataset(token=args.token, repo_id=args.dataset_repo_id, dataset_dir=args.dataset_dir, mode=args.mode)


if __name__ == "__main__":
    main()
