import os
import sys
import json
import tempfile
from pathlib import Path
from dotenv import load_dotenv

# Add local path
sys.path.append(str(Path(__file__).parent.parent))

DEFAULT_DATASET_REPO = "daominhwysi/synthetic-seq-labelling-vi-exam-v2"
DEFAULT_DATASET_DIR  = "output/dataset"


# ---------------------------------------------------------------------------
# Dataset card (README.md)
# ---------------------------------------------------------------------------

def _generate_dataset_card(repo_id: str) -> str:
    return f"""\
---
language:
- vi
license: apache-2.0
task_categories:
- token-classification
task_ids:
- named-entity-recognition
tags:
- vietnamese
- exam
- sequence-labeling
- educational
- synthetic
pretty_name: Vietnamese Exam Sequence Labelling Dataset
---

# Vietnamese Exam Sequence Labelling Dataset

A synthetic + real-data dataset for **token-level sequence labelling** of Vietnamese educational exam papers.
Generated by the [sequence-labelling-data-generator](https://github.com/daominhwysi/vietnamese-exam-seq-labelling) pipeline using DeepSeek LLMs and real OCR-annotated exams.

## Task

Given raw exam text (possibly from OCR), label each token with one of the entity tags below so downstream models can automatically segment and extract structured exam components.

## Tag Set

| Tag | Description |
|---|---|
| `O` | Outside — not part of any entity |
| `B-question_label` / `I-question_label` | Question prefix indicators (`Câu 1:`, `Question 2.`) |
| `B-stem` / `I-stem` | Main question body text |
| `B-option_label` / `I-option_label` | Option letter prefixes (`A.`, `B.`, `a)`) |
| `B-option_text` / `I-option_text` | Option content text |
| `B-stimulus` / `I-stimulus` | Shared reading passage / stimulus block for group questions |
| `B-section` / `I-section` | Section headers and exam directions |

## Data Fields

Each sample in `train.jsonl`, `val.jsonl`, `test.jsonl` contains:

```json
{{
  "tokens":         ["▁Câu", "▁1", ".", "▁Cho", "..."],
  "input_ids":      [0, 12, 34, 56, ...],
  "attention_mask": [1, 1, 1, 1, ...],
  "labels":         [1, 2, 0, 3, ...],
  "tags":           ["B-question_label", "I-question_label", "O", "B-stem", ...],
  "metadata": {{
    "subject":       "physics",
    "grade":         11,
    "is_real":       false,
    "exam_id":       "exam_abc123",
    "max_len":       512,
    "stride":        128,
    "chunk_idx":     0,
    "total_chunks":  1
  }}
}}
```

Label IDs are defined in `label_mapping.json`.

## Splits

| Split | File |
|---|---|
| Train | `train.jsonl` |
| Validation | `val.jsonl` |
| Test | `test.jsonl` |

## Subjects

`economics_law`, `geography`, `history`, `math_algebra`, `math_geometry`, `physics`, `chemistry`, `english`, `literature`

## Grades

8 · 9 · 10 · 11 · 12

## XML Annotation Files

The `xml/` folder contains human-readable inline-tagged XML files reconstructed from real and synthetic exams, matching the annotation format used during data creation:

```xml
<question_label>Câu 1.</question_label> <stem>Cho phương trình $x^2 - 5x + 6 = 0$.</stem>
<option_label>A.</option_label> <option_text>x = 2 hoặc x = 3</option_text>
```

## Citation

```bibtex
@misc{{vi-exam-seq-labelling,
  title  = {{Vietnamese Exam Sequence Labelling Dataset}},
  author = {{daominhwysi}},
  year   = {{2025}},
  url    = {{https://huggingface.co/datasets/{repo_id}}}
}}
```
"""


# ---------------------------------------------------------------------------
# Main upload function
# ---------------------------------------------------------------------------

def upload_dataset(token=None, repo_id=None, dataset_dir=None):
    """
    Upload the tokenized dataset splits + XML annotation files to HF Hub.
    Also generates and uploads a dataset card (README.md).

    XML annotation files are expected to live in `{dataset_dir}/xml/` and are
    uploaded automatically as part of the dataset folder (generated by prepare-offline-dataset).

    Args:
        token:       HF write token (falls back to HF_TOKEN env var).
        repo_id:     Target HF dataset repository ID.
        dataset_dir: Local folder containing train/val/test JSONL + label_mapping.json + xml/.
    """
    load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent.parent / ".env")

    if not token:
        token = os.getenv("HF_TOKEN")
    if not token:
        try:
            from huggingface_hub import get_token
            token = get_token()
        except ImportError:
            pass
    if not token:
        print("Error: HF_TOKEN not found in environment or huggingface-cli cache. Please log in with `hf auth login` or set HF_TOKEN.")
        sys.exit(1)

    if not repo_id:
        repo_id = DEFAULT_DATASET_REPO

    if not dataset_dir:
        dataset_dir = DEFAULT_DATASET_DIR

    dataset_path = Path(dataset_dir)
    if not dataset_path.exists():
        print(f"Error: Dataset directory '{dataset_dir}' does not exist.")
        sys.exit(1)

    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        print("Error: 'huggingface_hub' is not installed.")
        sys.exit(1)

    api = HfApi(token=token)

    print(f"Ensuring repository '{repo_id}' exists on Hugging Face Hub...")
    try:
        create_repo(repo_id=repo_id, repo_type="dataset", token=token, exist_ok=True)
        print("Repository is ready.")
    except Exception as e:
        print(f"Notice during repository creation: {e}")

    # 1. Generate and upload the dataset README --------------------------------
    print("Generating dataset card (README.md)...")
    readme_content = _generate_dataset_card(repo_id)
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", encoding="utf-8", delete=False
    ) as tmp:
        tmp.write(readme_content)
        tmp_readme_path = tmp.name

    try:
        api.upload_file(
            path_or_fileobj=tmp_readme_path,
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="dataset",
            commit_message="Add dataset card (README.md)",
        )
        print("  Uploaded README.md")
    except Exception as e:
        print(f"  Warning: Could not upload README.md: {e}")
    finally:
        Path(tmp_readme_path).unlink(missing_ok=True)

    # 2. Upload dataset splits + label_mapping + xml/ subfolder ---------------
    print(f"\nUploading dataset from '{dataset_dir}' -> '{repo_id}' ...")
    xml_count = len(list((dataset_path / "xml").glob("*_annotated.xml"))) if (dataset_path / "xml").exists() else 0
    if xml_count:
        print(f"  (includes {xml_count} XML annotation file(s) in xml/)")
    try:
        api.upload_folder(
            folder_path=str(dataset_path),
            repo_id=repo_id,
            repo_type="dataset",
            commit_message="Upload synthetic sequence labelling dataset for Vietnamese exams",
        )
        print(f"  Uploaded dataset splits{' + XML annotations' if xml_count else ''}.")
    except Exception as e:
        print(f"Error uploading dataset: {e}")
        sys.exit(1)

    print(f"\nSuccess! Dataset at: https://huggingface.co/datasets/{repo_id}")


if __name__ == "__main__":
    upload_dataset()
